services:
  - type: web
    name: ellinaki
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: ellinaki-data
      mountPath: /data
      sizeGB: 1

